server:
  port: 8081
spring:
  application:
    name: aiyalucky
  datasource:
    url: jdbc:mysql://localhost:3306/aiyalucky?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver