server:
  port: 8081
spring:
  application:
    name: aiyalucky
  datasource:
    url: jdbc:mysql://www.aiyalucky.com:3306/allinone?useUnicode=true&characterEncoding=utf8
    username: root
    password: Xxw19900101
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml